export default [
  {
    index: 1,
    name: "Mazda",
    price: "$70,000",
    model: "CX 5",
    image: require("../../assets/images/ModelS.jpeg"),
  },
  {
    index: 2,
    name: "Hyundai",
    price: "$80,000",
    model: "Creta",
    image: require("../../assets/images/Model3.jpeg"),
  },
  {
    index: 3,
    name: "Tesla",
    price: "$30,000",
    model: "X",
    image: require("../../assets/images/ModelX.jpeg"),
  },
  {
    index: 4,
    name: "Tesla",
    price: "$40,000",
    model: "Y",
    image: require("../../assets/images/ModelY.jpeg"),
  },
  {
    index: 5,
    price: "$14,000",
    name: "Royel Enfield",
    model: "XM-1",
    image: require("../../assets/images/1.jpg"),
  },
  {
    index: 6,
    price: "$14,000",
    name: "Royel Enfield",
    model: "XM-2",
    image: require("../../assets/images/2.jpg"),
  },
  {
    index: 7,
    price: "$14,000",
    name: "Royel Enfield",
    model: "XM-3",
    image: require("../../assets/images/3.jpg"),
  },
  {
    index: 8,
    price: "$14,000",
    name: "Royel Enfield",
    model: "XM-4",
    image: require("../../assets/images/4.jpg"),
  },
  {
    index: 9,
    price: "$14,000",
    name: "Royel Enfield",
    model: "XM-4",
    image: require("../../assets/images/5.jpg"),
  },
];
