export default [{
  index: 1,
  name: 'Tesla',
  price: '$70,000',
  model: 'S',
  image: require('../../assets/images/ModelS.jpeg'),
}, {
  index: 2,
  name: 'Tesla',
  price: '$70,000',
  model: '3',
  image: require('../../assets/images/Model3.jpeg'),
}, {
  index: 3,
  name: 'Tesla',
  price: '$70,000',
  model: 'X',
  image: require('../../assets/images/ModelX.jpeg'),
}, {
  index: 4,
  name: 'Tesla',
  price: '$70,000',
  model: 'Y',
  image: require('../../assets/images/ModelY.jpeg'),
},
{
  index: 5,
  price: '$14,000',
  name: 'Royel Enfield',
  model: 'XM-1',
  image: require('../../assets/images/1.jpg'),
},
{
  index: 6,
  price: '$14,000',
  name: 'Royel Enfield',
  model: 'XM-2',
  image: require('../../assets/images/2.jpg'),
},
{
  index: 7,
  price: '$14,000',
  name: 'Royel Enfield',
  model: 'XM-3',
  image: require('../../assets/images/3.jpg'),
},
{
  index: 8,
  price: '$14,000',
  name: 'Royel Enfield',
  model: 'XM-4',
  image: require('../../assets/images/4.jpg'),
}];
